[project]
name = "prettymol"
version = "0.1.0"
description = "make molecules. pretty"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = ["biotite", "bpy", "molecularnodes"]
packages = [{ include = "prettymol", from = "src" }]

[dependency-groups]
dev = ["ipython", "jupyter", "pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
