project:
  type: website

website:
  title: "prettymol"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: examples.qmd
        text: Examples
      - text: Code Documentation
        menu:
          - href: api.html
            text: API
          - href: materials.html
            text: Materials
          - href: selections.html
            text: Selections
          - href: styles.html
            text: Styles

    right:
      - icon: github
        href: https://github.com/zachcp/prettymol

format:
  html:
    highlight-style: github
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
