project:
  type: website

website:
  title: "prettymol"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Styles.html
        text: Styles
      - href: Selections.html
        text: Selections

    right:
      - icon: github
        href: https://github.com/zachcp/prettymol

format:
  html:
    highlight-style: github
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
